### ISSUE TITLE
Secondary index sequence not shown in flowcell view

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/flowcelltool#62] opened 2017-08-04 08:57 UTC
Probably a simple bug in the template.

**Comment by mikkonie** [comment] 2018-02-21 17:12
This seems to be caused by `index_read_count` in FlowCell objects not getting correctly updated. Will investigate.

**Comment by mikkonie** [comment] 2018-02-22 09:11
Scratch my previous comment, I misunderstood the issue. This was indeed due to a missing bit in the templates. Will be fixed in the next commit.

**Closed** 2018-02-23 13:44 UTC
